name: fcleaner
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  disk_usage: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.3.0
  intl: ^0.20.2
  material_symbols_icons: ^4.2874.0
  os_cleaner:
    path: packages/os_cleaner
  path: ^1.9.0
  ui:
    path: packages/ui

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/work_sans/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/work_sans/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/work_sans/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/work_sans/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/work_sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/work_sans/WorkSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/work_sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/work_sans/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/work_sans/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/work_sans/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/work_sans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/work_sans/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/work_sans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/work_sans/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic

